name: PUll request comment
on:
  pull_request_target:
    types: [opened]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: comment on new prs
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `Hello @${{ github.actor }}! Thank you for your pull request. I will review it soon.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

