name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'John Smith'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

